using Newtonsoft.Json;
using NodeFlow.Core.Nodes;

namespace NodeFlow.Core.Graph
{
  /// <summary>
  ///   A bound ParameterDefinition in an Graph (a data connection between two NNodes). This is akin to
  ///   and edge in a graph.
  /// </summary>
  [JsonObject(MemberSerialization.OptIn)]
  public class ParameterBinding
  {
    #region Fields / Properties

    /// <summary>
    ///   The source parameter type this is bound to.
    /// </summary>
    [JsonProperty] public ParameterDefinition SourceParameterDefinition;

    /// <summary>
    ///   The target parameter type this is bound to. Probably the same as source.
    /// </summary>
    [JsonProperty] public ParameterDefinition TargetParameterDefinition;

    /// <summary>
    ///   The source node that generates the value for this parameter binding.
    /// </summary>
    [JsonProperty] public Node SourceNode;

    /// <summary>
    ///   The target node that accepts the value generated by SourceNode for this binding.
    /// </summary>
    [JsonProperty] public Node TargetNode;

    /// <summary>
    ///   Rather than set an input Node, primitive types can be bound to a literal value. This
    ///   is null otherwise.
    /// </summary>
    [JsonProperty] public string LiteralValue;

    #endregion

    /// <summary>
    ///   Create a node-to-node binding.
    /// </summary>
    public ParameterBinding(ParameterDefinition sourceParameterDefinition,
      ParameterDefinition targetParameterDefinition, Node sourceNode, Node targetNode)
    {
      SourceParameterDefinition = sourceParameterDefinition;
      TargetParameterDefinition = targetParameterDefinition;
      SourceNode = sourceNode;
      TargetNode = targetNode;
    }

    /// <summary>
    ///   Creates a literal-value binding.
    /// </summary>
    public ParameterBinding(ParameterDefinition targetParameterDefinition, Node targetNode, string literalValue)
    {
      TargetParameterDefinition = targetParameterDefinition;
      TargetNode = targetNode;
      LiteralValue = literalValue;
    }
  }
}